### ISSUE TITLE
你好 openvino是什么版本呢，另外IR文件是从哪里得到的呢

### ISSUE THREAD

**Issue by AAA-Fan** [adamydwang/insightface-openvino#1]
你好 openvino是什么版本呢，另外IR文件是从哪里得到的呢

**Comment by adamydwang** [comment]
建议采用openvino最新版本。当前最新版本2020.4
IR模型readme.txt中提供下载地址。原模型参考tf-insightface。转换方法可参考今日头条相关文章。


------------------------------------------------------------------
发件人：AAA-Fan <notifications@github.com>
发送时间：2020年7月16日(星期四) 01:57
收件人：adamydwang/insightface-openvino <insightface-openvino@noreply.github.com>
抄　送：Subscribed <subscribed@noreply.github.com>
主　题：[adamydwang/insightface-openvino] 你好 openvino是什么版本呢，另外IR文件是从哪里得到的呢 (#1)

你好 openvino是什么版本呢，另外IR文件是从哪里得到的呢
