### ISSUE TITLE
模型预处理问题

### ISSUE THREAD

**Issue by AAA-Fan** [adamydwang/insightface-openvino#2]
代码中insightface模型的输入是直接把像素值放里面，实际是不是添加要经过归一化处理过程呢

**Comment by adamydwang** [comment]
> 代码中insightface模型的输入是直接把像素值放里面，实际是不是添加要经过归一化处理过程呢

理论上是输入是需要归一化的，但是我这里的归一化操作固化到了Model里面，所以代码里就不需要了。

**Comment by AAA-Fan** [comment]
也就是说在ir转化时候已经预处理操作了吧，现在我们直接把opencv读取的bgr图输入就行了吧？

**Comment by adamydwang** [comment]
> 也就是说在ir转化时候已经预处理操作了吧，现在我们直接把opencv读取的bgr图输入就行了吧？
是的
